---

- name: Configure AWS Greengrass Cores
  hosts: all
  vars:

    greengrass_software_src: >-
      https://d1onfpft10uf5o.cloudfront.net/
      greengrass-core/downloads/1.8.1/
      greengrass-linux-armv7l-1.8.1.tar.gz

    python_packages:
      - awscli
      - botocore
      - boto3
      - AWSIoTPythonSDK

  tasks:

    - name: Install Python Dependencies
      become: yes
      become_user: root
      become_method: sudo
      pip:
        name: "{{ python_packages | join(', ') }}"
        state: present


    - name: Update Soft/Hard Link protection and Disable all IPv6
      become: yes
      become_user: root
      become_method: sudo
      blockinfile:
        dest: /etc/sysctl.d/98-rpi.conf
        block: |
          fs.protected_hardlinks = 1
          fs.protected_symlinks = 1
          net.ipv6.conf.all.disable_ipv6 = 1


    - name: Check Debian Stretch CGroups
      become: yes
      become_user: root
      become_method: sudo
      replace:
        path: /boot/cmdline.txt
        regexp: ' cgroup_enable=memory'
        replace: ''


    - name: Check Debian Stretch CGroups
      become: yes
      become_user: root
      become_method: sudo
      replace:
        path: /boot/cmdline.txt
        regexp: ' cgroup_memory=1'
        replace: ''


    - name: Enable Debian Stretch CGroups
      become: yes
      become_user: root
      become_method: sudo
      shell: sed -i 's/$/ cgroup_enable=memory cgroup_memory=1/' /boot/cmdline.txt
      args:
        warn: false


    - name: Download and Unpack Greengrass Software
      become: yes
      become_user: root
      become_method: sudo
      unarchive:
        src: "{{ greengrass_software_src }}"
        dest: /
        remote_src: yes


    - name: Create Greengrass Core User
      become: yes
      become_user: root
      become_method: sudo
      user:
        name: ggc_user
        state: present
        system: yes


    - name: Create Greengrass Core Group
      become: yes
      become_user: root
      become_method: sudo
      group:
        name: ggc_group
        state: present
        system: yes


    - name: Create Systemd Service for Greengrass
      become: yes
      become_user: root
      become_method: sudo
      blockinfile:
        path: /etc/systemd/system/greengrass.service
        create: yes
        block: |
          [Unit]
          Description=Greengrass Daemon
          [Service]
          Type=forking
          PIDFile=/var/run/greengrassd.pid
          Restart=on-failure
          ExecStart=/greengrass/ggc/core/greengrassd start
          ExecReload=/greengrass/ggc/core/greengrassd restart
          ExecStop=/greengrass/ggc/core/greengrassd stop
          [Install]
          WantedBy=multi-user.target


    - name: Start and Enable Greengrass Core
      become: yes
      become_user: root
      become_method: sudo
      systemd:
        name: greengrass
        state: started
        enabled: yes
